<a href="https://colab.research.google.com/github/SEKAR147/Demo-repo/blob/main/Let's_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Tensors

---
Creating a Tensor



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


### Introduction to tensors
Creating tensors:


In [ ]:
# Scaler
scaler = torch.tensor(8)
scaler

tensor(8)

In [ ]:
scaler.ndim

0

In [ ]:
#get tensor back as python int
scaler.item()

8

In [ ]:
#Vector
Vec = torch.tensor([9,9])
Vec

tensor([9, 9])

In [ ]:
Vec.ndim

1

In [ ]:
Vec.shape

torch.Size([2])

In [ ]:
# Matrix
mat = torch.tensor([[2,3],
                    [4,6]])
mat

tensor([[2, 3],
        [4, 6]])

In [ ]:
mat.ndim

2

In [ ]:
mat[1]

tensor([4, 6])

In [ ]:
mat.shape

torch.Size([2, 2])

In [ ]:
 #TENSORS
TENSOR = torch.tensor([[2,3,9],
                       [2,7,0],
                       [4,6,9]])

TENSOR

tensor([[2, 3, 9],
        [2, 7, 0],
        [4, 6, 9]])

In [ ]:
TENSOR.ndim

2

In [ ]:
TENSOR.shape

torch.Size([3, 3])

In [ ]:
ten = torch.tensor([[[1.,2,3],
                    [2.,3,4],
                    [4,5,6]]])
ten

tensor([[[1., 2., 3.],
         [2., 3., 4.],
         [4., 5., 6.]]])

# Random Tensors

# Why random tensors?

random tensors are important the way many neural networks learn is that they start wit tensors full of random numbers and then adjust those random numbers to better represent the data

 `Start with random numbers -> look at data -> update random numbers -> look at data-> Update random numbers`


In [ ]:
# create a random tensors of size(3,4)

random_ten = torch.rand(2,3,4)
random_ten

tensor([[[0.1179, 0.4311, 0.7872, 0.6384],
         [0.6804, 0.8284, 0.3375, 0.8740],
         [0.3504, 0.3911, 0.5798, 0.3860]],

        [[0.0909, 0.5266, 0.7761, 0.2742],
         [0.7740, 0.6713, 0.4588, 0.8799],
         [0.1916, 0.0577, 0.2925, 0.5534]]])

In [ ]:
random_ten.shape

torch.Size([2, 3, 4])

In [ ]:

random_ten.ndim

3

In [ ]:
# create a random tensors with similar shape to an image tensor
ran_image_size_ten = torch.rand((43,34,3)) # height ,width,colour channel
ran_image_size_ten.shape ,ran_image_size_ten.ndim

(torch.Size([43, 34, 3]), 3)

In [ ]:
ran_image_size_ten.ndim

3

### Zeros and Ones

In [ ]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
one = torch.ones(size=(4,5))
one

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
one.dtype

torch.float32

Creating a range of tensors and tensors -like


In [ ]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.__version__

'2.4.0+cu121'

In [ ]:
range_ten = torch.arange(start=0, end=100, step = 25)
range_ten

tensor([ 0, 25, 50, 75])

In [ ]:
### creating tensors like
ten_zeros = torch.zeros_like(input=range_ten)
ten_zeros

tensor([0, 0, 0, 0])

Tensors Datatypes


In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.4 , 4.4 , 5.0],
                                dtype=torch.float16,
                                device=None,
                               requires_grad=False)
float_32_tensor.dtype

torch.float16

In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.4 , 4.4 , 5.0],
                                dtype=torch.float16,
                                device=None,
                               requires_grad=False)
float_32_tensor

tensor([3.4004, 4.3984, 5.0000], dtype=torch.float16)

In [ ]:
  float_32_tensor.dtype

torch.float16

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.4004, 4.3984, 5.0000], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([11.5625, 19.3438, 25.0000], dtype=torch.float16)

In [ ]:
float_32_tensor ** float_16_tensor

tensor([  64.1875,  675.5000, 3124.0000], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3,4,5],dtype=torch.int64)
int_32_tensor

tensor([3, 4, 5])

In [ ]:
float_32_tensor * int_32_tensor

tensor([10.2031, 17.5938, 25.0000], dtype=torch.float16)

### Manipulating Tensors(Tensor Operation)
1. Addition
2. Subtraction
3. Multiplication (Elememt wise)
4. division
5. Matrix Multiplication



In [ ]:
# create a tensor and add 10 to it
ten= torch.tensor([1,2,3])
ten+10

tensor([11, 12, 13])

In [ ]:
torch.arange(1,10)
torch.arange

<function torch._VariableFunctionsClass.arange>

In [ ]:
ten = torch.tensor([1,2,3])
ten-10

tensor([-9, -8, -7])

In [ ]:
ten = torch.tensor([1,2,3])
ten - 10

tensor([-9, -8, -7])

In [ ]:
torch.tensor(10*10)

tensor(100)

 ### Matrix Multiplication
 Two main ways of performing multiplication  in neural net and DL
 1. Element wise Multiplication
 2. Matrix multiplication(dot product)

 there are to main rules that performing matmul needs to satisfy
 1. the **inner dimensions ** must match:
 2. outer dimensions


In [ ]:
### Element wise  Multiplication
print(ten,"*",ten )
print(f"Equals:{ten*ten}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
### Matrix Multiplication
torch.matmul(ten,ten)

tensor(14)

In [ ]:
%%time
value =0
for i in range(len(ten)):
  value += ten[i] * ten[i]
print(value)

tensor(14)
CPU times: user 1.67 ms, sys: 0 ns, total: 1.67 ms
Wall time: 1.7 ms


In [ ]:
 %%time
torch.matmul(ten,ten)

CPU times: user 104 µs, sys: 0 ns, total: 104 µs
Wall time: 109 µs


tensor(14)

In [ ]:
torch.matmul(torch.rand(2,4)), torch.rand(2,3)

TypeError: matmul() missing 1 required positional arguments: "other"

### One of the most errors in deep learning: Shape Errors



To fix out tensor shape issues, we can manipulate the shape of one our tensors using

In [ ]:
ten_a= torch.tesnor([[1,2],
                     [3,4],
                     [9,4],
                     [2,5]])
ten_b= torch.tesnor([[3,4],
                     [4,5],
                     [5,5]])
torch.matmul(ten_a,ten_b)



to fix our tensor shape issues ,we cam manipulate the shape of one of our tensors using a transpose
A transpose switches the axes or dimensions of given tensor

In [ ]:
ten_a.shape,ten_b.shape

In [ ]:
ten_b,ten_b.shape

To fix pur tensor shape issues, we can manipulate the shape of one of the our tensors using transpose

A **Transpose** switches the axes or dimensions of given tensor

In [ ]:
ten_b.T,

In [ ]:
ten_b.T.shape

In [ ]:
# The Matrix multiplication operations  works tensor tens_b is transposed
torch.matmul(ten_a, ten_b.T), ten_b.T.shape

### Finding the min,max,sum and etc (tensor aggrigation)

In [ ]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.max()

tensor(90)

In [ ]:
x[0]

tensor(0)

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[5]

tensor(50)

In [ ]:
x.argmax()

tensor(9)

### Reshaping,stacking, squeezing and unsqueesing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View: Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking: Combine multiple tensors on top of each other(vstack) or side by side(hstack)
* Squeeze: remove all '1' dimensions from a tensor
* Unsqueeze: add a '1' dimension to a target tensor
* permute: Return a view of the input with dinmensions permuted(swapped) in certain way

In [ ]:
import torch

x= torch.arange(1.,10)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add a extra dimension
x_reshape = x.reshape(1,9)
x_reshape,x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
 # change the view
z= x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:,0] = 3
z,x

(tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stack = torch.stack([x,x,x,x], dim=0)
x_stack

tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshape

tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshape.shape

torch.Size([1, 9])

In [ ]:
x_reshape.squeeze()

tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshape.squeeze().shape

torch.Size([9])

In [ ]:
#torch.permute - rearranges the target the tensor in a specified order
x_original = torch.rand(size=(22,3,3))
x_permuted = x_original.permute(2,0,1)
print(f"prevoius shape:{x_original.shape}")
print(f"new shape:{x_permuted.shape}")

prevoius shape:torch.Size([22, 3, 3])
new shape:torch.Size([3, 22, 3])


##indexing (Selecting data from tensors)

indexing with pytorch is similar to  indexing in Numpy

In [ ]:
import torch

In [ ]:
#create a tensor

import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
#let's index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [ ]:
# you can also use ":" to select "all" of a target deminsion
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

#pytorch tensors and numpy
Numpy is a poplular scientific pytjon computing library


In [ ]:
#numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning : when converting from numpy -> pytorch reflects numpy's datatype of float64 unless specified otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0,9.0).dtype

torch.float32

In [ ]:
# change the value of array, what will do this 'tensor?'
array = array+1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tensors to numpy array
tensor = torch.ones(9)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# change the tensor , what happens to 'numpy_tensors'
tensor = tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#Reproducibility (trying to take random out of random)
start with random numbers -> tensor operations -> update random numbers to try and make them better representions of the data -. again ->again - > again

to reduce the randomnes in neural networks and pytorch comes the concept of a "random seed"

Essentionlly what the random seed does is 'flavour ' the randomness

In [ ]:
torch.rand(3,4)

tensor([[0.5971, 0.9291, 0.6079, 0.9786],
        [0.7864, 0.0822, 0.7376, 0.6457],
        [0.7741, 0.8237, 0.4842, 0.9572]])

In [ ]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5164, 0.4106, 0.0398, 0.0513],
        [0.2305, 0.4774, 0.9198, 0.8033],
        [0.4709, 0.2902, 0.1786, 0.8470]])
tensor([[0.3670, 0.9114, 0.6396, 0.1325],
        [0.0459, 0.7077, 0.5386, 0.7557],
        [0.2183, 0.7268, 0.8363, 0.4190]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Lets make some random but reprdocible tensors

import torch

# Set the random seed
RANDOM_SEED = 23
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.4283, 0.2889, 0.4224, 0.3571],
        [0.9577, 0.1100, 0.2933, 0.9205],
        [0.5876, 0.1299, 0.6729, 0.1028]])
tensor([[0.4283, 0.2889, 0.4224, 0.3571],
        [0.9577, 0.1100, 0.2933, 0.9205],
        [0.5876, 0.1299, 0.6729, 0.1028]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and pytorch objects on the GPUs

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
### check for GPU acceess with pytorch
import torch
torch.cuda.is_available()

False

In [ ]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
torch.cuda.device_count()

0

 # putting tensors on the gpu's


In [ ]:
 #3. putting tensors on the gpu'smples.
 tensor = torch.tensor([1,2,3])
 print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

# 4. Moving tensors back to the CPU

In [ ]:
#if tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [ ]:
# To fix the gpu tensor with numpy issue , we can firstset it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3])